### ISSUE TITLE
[ose-scaler] Erroring in process_playbook_json_output after successful completion of Scaler Playbook 

### ISSUE THREAD

**Issue by philipakash** [aws-quickstart/quickstart-redhat-openshift#102]
The python script adds the new node to the openshift Cluster but fails when it starts processing the Ansible Playbook JSON Output. Not sure If I am missing something .
(Playbook Execution is successful as Node is added to the cluster and in ready state)
----------ERROR-------
Traceback (most recent call last):
  File "/bin/aws-ose-qs-scale", line 14, in <module>
    sys.exit(main())
  File "/bin/aws-ose-qs-scale", line 11, in main
    return aws_openshift_quickstart.scaler.main()
  File "/usr/lib/python2.7/site-packages/aws_openshift_quickstart/scaler.py", line 204, in main
    scale_inventory_groups()
  File "/usr/lib/python2.7/site-packages/aws_openshift_quickstart/scaler.py", line 163, in scale_inventory_groups
    _is.process_playbook_json_output(jout_file=file_cat[cat], category=cat)
  File "/usr/lib/python2.7/site-packages/aws_openshift_quickstart/utils.py", line 361, in process_playbook_json_output
    json_start_idx = all_output.index('{\n')
ValueError: '{\n' is not in list
failed to run commands: exit status 1

I found the temporary Log files in /tmp directory and they show success.
Are the temp files supposed to be converted to JSON?

**Comment by philipakash** [comment]
- "sed -i 's/#stdout_callback.*/stdout_callback = json/g' /etc/ansible/ansible.cfg\
i think I missed Ansible Output settings ?

**Comment by philipakash** [comment]
Closing this as its fixed :-)
