### ISSUE TITLE
Ansible Config server failed to update hosts file new node 

### ISSUE THREAD

**Issue by yakkaty12** [aws-quickstart/quickstart-redhat-openshift#234]
Hi Team,

We have deployed ocp cluster by using AWS quickstart template and build was successful, now we are testing resilient test cases ( terminated one master/etcd/node ) to check it will scale up automatically or not . 

Ansible config server failed to update /etc/ansible/hosts file new master and unable to clear terminated master entry from /etc/ansible/hosts file.

we are seeing below errors in logs can you please help.

making schedulable
setting node group
making schedulable
setting node group
making schedulable
setting node group

----------ERROR-------
Traceback (most recent call last):
  File "/bin/aws-ose-qs-scale", line 17, in <module>
    sys.exit(main())
  File "/bin/aws-ose-qs-scale", line 13, in main
    return aws_openshift_quickstart.scaler.main()
  File "/usr/lib/python2.7/site-packages/aws_openshift_quickstart/scaler.py", line 391, in main
    scale_inventory_groups(ocp_version=args.ocp_version)
  File "/usr/lib/python2.7/site-packages/aws_openshift_quickstart/scaler.py", line 284, in scale_inventory_groups
    _is.process_pipeline()
  File "/usr/lib/python2.7/site-packages/aws_openshift_quickstart/utils.py", line 292, in process_pipeline
    cls.unsubscribe_nodes(cls.nodes_to_remove['combined'])
  File "/usr/lib/python2.7/site-packages/aws_openshift_quickstart/utils.py", line 353, in unsubscribe_nodes
    for tag in tags:
  File "/usr/lib/python2.7/site-packages/aws_openshift_quickstart/utils.py", line 326, in get_UUID
    while i < len(local_instance.tags):
  File "/usr/lib/python2.7/site-packages/boto3/resources/factory.py", line 345, in property_loader
    return self.meta.data.get(name)
AttributeError: 'NoneType' object has no attribute 'get'
failed to run commands: exit status 1

Thanks,
Chandra.

**Comment by yakkaty12** [comment]
Hi Team,

Redeployed with Ansible from Git option but still facing same issue, can someone please help to resolve this issue.

making schedulable
setting node group
making schedulable
setting node group
making schedulable
setting node group

----------ERROR-------
Traceback (most recent call last):
  File "/bin/aws-ose-qs-scale", line 17, in <module>
    sys.exit(main())
  File "/bin/aws-ose-qs-scale", line 13, in main
    return aws_openshift_quickstart.scaler.main()
  File "/usr/lib/python2.7/site-packages/aws_openshift_quickstart/scaler.py", line 391, in main
    scale_inventory_groups(ocp_version=args.ocp_version)
  File "/usr/lib/python2.7/site-packages/aws_openshift_quickstart/scaler.py", line 284, in scale_inventory_groups
    _is.process_pipeline()
  File "/usr/lib/python2.7/site-packages/aws_openshift_quickstart/utils.py", line 292, in process_pipeline
    cls.unsubscribe_nodes(cls.nodes_to_remove['combined'])
  File "/usr/lib/python2.7/site-packages/aws_openshift_quickstart/utils.py", line 357, in unsubscribe_nodes
    auth = cls.get_secret()
  File "/usr/lib/python2.7/site-packages/aws_openshift_quickstart/utils.py", line 336, in get_secret
    region_name = region.text[:-1]
AttributeError: 'unicode' object has no attribute 'text'
failed to run commands: exit status 1


Thanks,
Chandra.

**Comment by Ravi-OSI** [comment]
+1

Hello, 

Facing the same issue as informed by yakkaty12, ASG is adding the ec2 instances but they are not joining the OC cluster.
