### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by waynedovey** [aws-quickstart/quickstart-redhat-openshift#60]
I have found another problem when the scale operation run. It seems like the Ansible output is failing to parse.

```
openshift-quickstart-scaling.log

2018-03-02T00:54:29UTC scaler.py  INFO    : We've detected that we need to run ansible playbooks to scale up the cluster!
2018-03-02T00:54:29UTC scaler.py  INFO    : We will run the following ansible command:
2018-03-02T00:54:29UTC scaler.py  INFO    : ansible-playbook /usr/share/ansible/openshift-ansible/scaleup_wrapper.yml --extra-vars="{'scaling_category': 'node', 'target': 'provision_in_progress'}"
2018-03-02T00:54:29UTC scaler.py  INFO    : We will run the following ansible command:
2018-03-02T00:54:29UTC scaler.py  INFO    : ansible-playbook /usr/share/ansible/openshift-ansible/scaleup_wrapper.yml --extra-vars="{'scaling_category': 'master', 'target': 'provision_in_progress'}"
2018-03-02T00:54:29UTC scaler.py  INFO    : We will run the following ansible command:
2018-03-02T00:54:29UTC scaler.py  INFO    : ansible-playbook /usr/share/ansible/openshift-ansible/scaleup_wrapper.yml --extra-vars="{'scaling_category': 'etcd', 'target': 'provision_in_progress'}"
2018-03-02T00:54:29UTC scaler.py  INFO    : We have 3 ansible playbooks running!
2018-03-02T00:55:01UTC scaler.py  INFO    : - A process completed. We're parsing it...

# /bin/aws-ose-qs-scale --scale-in-progress --debug
Traceback (most recent call last):
  File "/bin/aws-ose-qs-scale", line 14, in <module>
    sys.exit(main())
  File "/bin/aws-ose-qs-scale", line 11, in main
    return aws_openshift_quickstart.scaler.main()
  File "/usr/lib/python2.7/site-packages/aws_openshift_quickstart/scaler.py", line 204, in main
    scale_inventory_groups()
  File "/usr/lib/python2.7/site-packages/aws_openshift_quickstart/scaler.py", line 163, in scale_inventory_groups
    _is.process_playbook_json_output(jout_file=file_cat[cat], category=cat)
  File "/usr/lib/python2.7/site-packages/aws_openshift_quickstart/utils.py", line 358, in process_playbook_json_output
    j = json.loads(all_output[idx])['stats']
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by agamzn** [comment]
This is why that's doing that. Working on a fix.

```
Pausing for 10 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)^M
        to retry, use: --limit @/usr/share/ansible/openshift-ansible/scaleup_wrapper.retry
{
    "plays": [
        {
            "play": {
                "id": "124ba49f-9c9c-7e6e-bd5c-00000000000f",
                "name": "Scale up"
            },
            "tasks": [
                {
                    "hosts": {
                        "ip-10-0-20-227.ec2.internal": {
                            "_ansible_no_log": false,
                            "changed": false,
                            "elapsed": 0
                        },
                        "ip-10-0-30-97.ec2.internal": {
                            "_ansible_no_log": false,
                            "changed": false,
                            "elapsed": 117
                        }
                    },
```

**Comment by agamzn** [comment]
Adding this here for documentation purposes. 

In the course of fixing this, I found an error in an unrelated function.  This line should read `_diff.seconds`. I'm including the relevant commit in the subsequent PR. 

https://github.com/aws-quickstart/quickstart-redhat-openshift/blob/462a49d8e4abb222ffa59908439011db86039206/scripts/scaling/aws_openshift_quickstart/utils.py#L517
